name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r yt_allinone/requirements.txt
          pip install ruff flake8
      - name: Lint (ruff)
        run: ruff check .
      - name: Lint (flake8)
        run: flake8 .
      - name: Test
        run: pytest -q

